-- Launch taxonomy for Pune. Generated by scripts/gen-taxonomy-sql.mjs from scripts/taxonomy.mjs.
--> statement-breakpoint
INSERT INTO suburb (id, name, city, sort_order, active) VALUES ('wagholi', 'Wagholi', 'Pune', 0, 1);
--> statement-breakpoint
INSERT INTO suburb (id, name, city, sort_order, active) VALUES ('hadapsar', 'Hadapsar', 'Pune', 1, 1);
--> statement-breakpoint
INSERT INTO suburb (id, name, city, sort_order, active) VALUES ('wakad', 'Wakad', 'Pune', 2, 1);
--> statement-breakpoint
INSERT INTO suburb (id, name, city, sort_order, active) VALUES ('baner', 'Baner', 'Pune', 3, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('entrepreneurship', 'Entrepreneurship & Money', '🚀', 'Founders, wannabe founders and spreadsheet romantics.', 0, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('nikhil-kamath-podcast', 'entrepreneurship', 'Nikhil Kamath''s WTF podcast', '🎙️', 'For people who have opinions on episode 47.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('nikhil-kamath-podcast-q1', 'nikhil-kamath-podcast', 'Which kind of episode sticks with you most?', 'single', '["The ones about failure","The ones about money","The ones about health","The founder origin stories","The ones about AI"]', 1, 'Episodes that stick: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('nikhil-kamath-podcast-q2', 'nikhil-kamath-podcast', 'Your honest listening style?', 'single', '["Every episode, full length","Only the guests I know","1.5x while commuting","Clips on Instagram, sorry"]', 1, 'Listens: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('nikhil-kamath-podcast-q3', 'nikhil-kamath-podcast', 'Hot take you''d defend over cutting chai:', 'single', '["UPI beats crypto","College is optional now","D2C is overhyped","Bootstrapping > VC money","Tier-2 cities are the future"]', 1, 'Will defend "{answer}" over cutting chai.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('indie-hacking', 'entrepreneurship', 'Indie hacking & side projects', '🛠️', 'Shipping things at 2am, fixing them at 3am.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indie-hacking-q1', 'indie-hacking', 'Where''s your side project right now?', 'single', '["Just an idea in Notes","Half-built, abandoned","Launched, zero users","Launched, a few users","Making real money"]', 1, 'Side project status: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indie-hacking-q2', 'indie-hacking', 'What do you love building?', 'multi', '["SaaS tools","Mobile apps","Newsletters","Communities","Physical products","Games"]', 2, 'Loves building: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indie-hacking-q3', 'indie-hacking', 'Biggest weakness as a builder?', 'single', '["Marketing","Finishing things","Picking one idea","Design","Pricing"]', 1, 'Admitted weak spot: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('personal-finance', 'entrepreneurship', 'Investing & personal finance', '📈', 'SIPs, spreadsheets and the eternal FD debate.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('personal-finance-q1', 'personal-finance', 'Your investing personality?', 'single', '["Index fund and chill","Stock picker","Real estate believer","Gold and FD loyalist","Still figuring it out"]', 1, 'Investing personality: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('personal-finance-q2', 'personal-finance', 'Money book that changed you?', 'single', '["Psychology of Money","Rich Dad Poor Dad","Let''s Talk Money","The Intelligent Investor","Haven''t read one yet"]', 1, 'Shaped by "{answer}".', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('personal-finance-q3', 'personal-finance', 'Most controversial money opinion?', 'single', '["Renting beats buying","Insurance is not investment","Crypto deserves 5%","Lifestyle creep is fine","Early retirement is overrated"]', 1, 'Quietly believes "{answer}".', 2, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('books', 'Books & Ideas', '📚', 'Margins full of notes, TBR piles out of control.', 1, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('marathi-literature', 'books', 'Marathi literature', '📖', 'Pu La, Kusumagraj and long arguments about both.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-literature-q1', 'marathi-literature', 'Who are you reading on a lazy Sunday?', 'single', '["Pu La Deshpande","V. P. Kale","Ratnakar Matkari","Narayan Dharap","Contemporary poets"]', 1, 'Lazy-Sunday author: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-literature-q2', 'marathi-literature', 'Favourite form?', 'single', '["Short stories","Poetry","Novels","Plays","Essays"]', 1, 'Falls hardest for: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-literature-q3', 'marathi-literature', 'Reading habit?', 'single', '["Paperbacks only","Kindle","Audiobooks","Library regular","Rereads old favourites"]', 1, 'Reading habit: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('non-fiction-nerds', 'books', 'Non-fiction nerds', '🧠', 'Ask them about Sapiens. Actually, don''t.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('non-fiction-nerds-q1', 'non-fiction-nerds', 'Topics you can''t stop reading about?', 'multi', '["History","Psychology","Economics","Science","Biographies","Geopolitics"]', 2, 'Can''t stop reading about: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('non-fiction-nerds-q2', 'non-fiction-nerds', 'Book you recommend too often?', 'single', '["Sapiens","Atomic Habits","Thinking, Fast and Slow","Why We Sleep","The Gene"]', 1, 'Recommends "{answer}" a little too often.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('non-fiction-nerds-q3', 'non-fiction-nerds', 'How do you take notes?', 'single', '["Underline everything","Notion database","Don''t, I remember","Tweet threads","Tell friends at dinner"]', 1, 'Note-taking style: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('philosophy', 'books', 'Philosophy & big questions', '🤔', 'Is a vada pav a sandwich? Let''s discuss for three hours.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('philosophy-q1', 'philosophy', 'Which school of thought feels like home?', 'single', '["Stoicism","Existentialism","Vedanta","Buddhism","Absurdism","Still shopping"]', 1, 'Philosophical home: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('philosophy-q2', 'philosophy', 'The question that keeps you up:', 'single', '["Free will","Meaning of life","Consciousness","Ethics of AI","What is a good life"]', 1, 'Lies awake thinking about: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('philosophy-q3', 'philosophy', 'Debate style?', 'single', '["Devil''s advocate","Socratic questions","Quote-heavy","Calm listener","Loud and passionate"]', 1, 'Debate style: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('music', 'Music', '🎧', 'Headphones in, opinions out.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('indian-indie', 'music', 'Indian indie', '🎸', 'Prateek Kuhad crying sessions welcome.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indian-indie-q1', 'indian-indie', 'Artists on repeat?', 'multi', '["Prateek Kuhad","When Chai Met Toast","The Local Train","Anuv Jain","Seedhe Maut","Ritviz"]', 2, 'On repeat: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indian-indie-q2', 'indian-indie', 'Gig habit?', 'single', '["Every weekend gig","Big concerts only","Bedroom listener","Plays guitar along","Discovers bands first"]', 1, 'Gig habit: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('indian-indie-q3', 'indian-indie', 'Best setting for indie music?', 'single', '["Rainy drive to Lonavala","Late-night work","Sunset terrace","Solo café","Shared earphones"]', 1, 'Indie hits hardest on a: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('hindustani-classical', 'music', 'Hindustani classical', '🎶', 'Sawai Gandharva season is our Christmas.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('hindustani-classical-q1', 'hindustani-classical', 'Your relationship with classical?', 'single', '["Trained for years","Learning now","Devoted listener","Curious beginner"]', 1, 'Relationship with classical: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('hindustani-classical-q2', 'hindustani-classical', 'Raga for a monsoon evening?', 'single', '["Miyan ki Malhar","Yaman","Bhimpalasi","Darbari","Bageshri"]', 1, 'Monsoon-evening raga: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('hindustani-classical-q3', 'hindustani-classical', 'Instrument that gets you?', 'single', '["Sitar","Sarod","Bansuri","Tabla","Vocals","Santoor"]', 1, 'Melts for: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('making-beats', 'music', 'Making beats', '🎛️', 'FL Studio, Ableton or a phone and a dream.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('making-beats-q1', 'making-beats', 'Your setup?', 'single', '["Ableton","FL Studio","Logic","Phone apps","Hardware only"]', 1, 'Beat lab: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('making-beats-q2', 'making-beats', 'Genres you produce?', 'multi', '["Lo-fi","Hip-hop","House","Bollywood remixes","Ambient","Indie pop"]', 2, 'Cooks up: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('making-beats-q3', 'making-beats', 'Where are you at?', 'single', '["Just started","Finished a few tracks","Released on Spotify","Doing gigs"]', 1, 'Producer status: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('outdoors', 'Outdoors & Fitness', '🥾', 'Sahyadris on weekends, sore legs on Mondays.', 3, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('sahyadri-treks', 'outdoors', 'Sahyadri treks & forts', '⛰️', 'Sinhagad at sunrise counts as cardio and therapy.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('sahyadri-treks-q1', 'sahyadri-treks', 'Favourite fort?', 'single', '["Sinhagad","Rajgad","Torna","Harihar","Lohagad","Kalsubai peak"]', 1, 'Would climb {answer} again tomorrow.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('sahyadri-treks-q2', 'sahyadri-treks', 'Trek style?', 'single', '["Night treks","Sunrise summits","Monsoon waterfalls","Solo with a playlist","Big group chaos"]', 1, 'Trek style: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('sahyadri-treks-q3', 'sahyadri-treks', 'Mandatory trek snack?', 'single', '["Kanda bhaji at the top","Nimbu sharbat","Parle-G","Dry fruits like a pro","Maggi at the base"]', 1, 'Non-negotiable trek snack: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('running', 'outdoors', 'Running', '🏃', '5am alarms and finisher medals.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('running-q1', 'running', 'Your distance?', 'single', '["Just started 5Ks","10K regular","Half marathons","Full marathons","Ultra, send help"]', 1, 'Distance: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('running-q2', 'running', 'Where do you run?', 'single', '["Riverside paths","Society loops","Treadmill","Hill routes","Wherever the playlist takes me"]', 1, 'Running turf: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('running-q3', 'running', 'Why do you run?', 'single', '["Clear my head","Chasing a PB","Social run club","Food permission","Started for a bet"]', 1, 'Runs because: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('cycling', 'outdoors', 'Cycling', '🚲', 'Weekend rides to Khadakwasla and beyond.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('cycling-q1', 'cycling', 'Your ride?', 'single', '["Road bike","MTB","Hybrid","Electric","Rented on weekends"]', 1, 'Ride of choice: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('cycling-q2', 'cycling', 'Ideal Sunday ride?', 'single', '["Khadakwasla loop","Mulshi road","City café hopping","Long highway miles","Trails and mud"]', 1, 'Ideal Sunday ride: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('cycling-q3', 'cycling', 'Cycling personality?', 'single', '["Strava segment hunter","Chai-stop enthusiast","Gear nerd","Commuter","Solo meditator"]', 1, 'Cycling personality: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('tech', 'Tech & Building', '💻', 'Terminal tabs open, side quests pending.', 4, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('ai-tinkering', 'tech', 'AI tinkering', '🤖', 'Prompting, fine-tuning, and arguing about agents.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('ai-tinkering-q1', 'ai-tinkering', 'What are you tinkering with?', 'multi', '["Chatbots","Agents","Image models","Local LLMs","Voice AI","AI for Indian languages"]', 2, 'Currently tinkering with: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('ai-tinkering-q2', 'ai-tinkering', 'Your AI stance?', 'single', '["Accelerate everything","Cautiously excited","Mostly skeptical","Just here for the memes"]', 1, 'AI stance: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('ai-tinkering-q3', 'ai-tinkering', 'Most useful thing AI did for you?', 'single', '["Wrote my code","Explained a concept","Planned a trip","Fixed my resume","Helped me cook"]', 1, 'Best AI moment: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('open-source', 'tech', 'Open source', '🐙', 'Green squares and good first issues.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('open-source-q1', 'open-source', 'Your open-source life?', 'single', '["Maintainer","Regular contributor","Made one PR once","Want to start","Mostly star repos"]', 1, 'Open-source life: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('open-source-q2', 'open-source', 'Languages you love?', 'multi', '["Python","TypeScript","Go","Rust","Java","C++"]', 2, 'Writes for fun in: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('open-source-q3', 'open-source', 'Tabs or spaces?', 'single', '["Tabs","Spaces","Whatever the formatter says","Don''t start this"]', 1, 'On tabs vs spaces: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('mechanical-keyboards', 'tech', 'Mechanical keyboards', '⌨️', 'Thock or clack, choose wisely.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('mechanical-keyboards-q1', 'mechanical-keyboards', 'Switch preference?', 'single', '["Linear","Tactile","Clicky","Silent","I just like keycaps"]', 1, 'Switch loyalty: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('mechanical-keyboards-q2', 'mechanical-keyboards', 'Layout?', 'single', '["Full size","TKL","75%","60%","Split ergonomic"]', 1, 'Layout: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('mechanical-keyboards-q3', 'mechanical-keyboards', 'How deep is the rabbit hole?', 'single', '["One nice board","Two or three","I build my own","I''ve lost count"]', 1, 'Keyboard collection: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO category (id, name, emoji, blurb, sort_order, active) VALUES ('screen', 'Films & Shows', '🎬', 'Letterboxd logs and strong reviews.', 5, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('marathi-cinema', 'screen', 'Marathi cinema', '🎞️', 'From Sairat to Shwaas and everything between.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-cinema-q1', 'marathi-cinema', 'A Marathi film everyone should see?', 'single', '["Sairat","Court","Shwaas","Natsamrat","Killa","Fandry"]', 1, 'Will make you watch {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-cinema-q2', 'marathi-cinema', 'Theatre or OTT?', 'single', '["First-day theatre","Waits for OTT","Only festival screenings","Natak over cinema"]', 1, 'Watches: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('marathi-cinema-q3', 'marathi-cinema', 'What makes a film great?', 'single', '["Writing","Acting","Music","Cinematography","Ending that wrecks you"]', 1, 'Great films live and die by: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('anime', 'screen', 'Anime', '🍥', 'Subs over dubs (mostly).', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('anime-q1', 'anime', 'Your anime era?', 'multi', '["Naruto days","Attack on Titan","One Piece forever","Studio Ghibli","Jujutsu Kaisen","Slice of life"]', 2, 'Anime era: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('anime-q2', 'anime', 'Subs or dubs?', 'single', '["Subs only","Dubs are fine","Hindi dubs nostalgia","Read the manga instead"]', 1, 'Subs vs dubs: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('anime-q3', 'anime', 'Watching style?', 'single', '["Binge a season overnight","Weekly with the hype","Rewatch comfort shows","Only finished series"]', 1, 'Watches: {answer}.', 2, 1);
--> statement-breakpoint
INSERT INTO subcategory (id, category_id, name, emoji, blurb, sort_order, active) VALUES ('true-crime-docs', 'screen', 'True crime & docs', '🕵️', 'Armchair detectives assemble.', 2, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('true-crime-docs-q1', 'true-crime-docs', 'Your doc genre?', 'single', '["True crime","Nature","Scams and frauds","Sports","History","Food"]', 1, 'Doc obsession: {answer}.', 0, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('true-crime-docs-q2', 'true-crime-docs', 'Format?', 'single', '["Netflix series","YouTube deep dives","Podcasts","Long-form articles"]', 1, 'Consumes it via: {answer}.', 1, 1);
--> statement-breakpoint
INSERT INTO prompt (id, subcategory_id, question, kind, options, max_select, template, sort_order, active) VALUES ('true-crime-docs-q3', 'true-crime-docs', 'Detective energy?', 'single', '["Solves it in episode 1","Gets scared, keeps watching","Researches after","Just likes the music"]', 1, 'Detective energy: {answer}.', 2, 1);
